name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dc: [ldc-latest, dmd-latest]
        include:
          - os: ubuntu-22.04
            dc: gdc-12

    steps:
    - uses: actions/checkout@v2

    - name: Install D compiler
      if: matrix.dc == 'ldc-latest' || matrix.dc == 'dmd-latest'
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: Install GDC
      if: matrix.dc == 'gdc-12'
      run: |
        sudo apt-get install gdc-12
        wget https://github.com/dlang/dub/releases/download/v1.23.0/dub-v1.23.0-linux-x86_64.tar.gz
        tar xvf dub-v1.23.0-linux-x86_64.tar.gz

    - name: 'Build & Test'
      if: matrix.dc != 'gdc-12'
      run: |
        dub build
        dub test

    - name: 'Build & Test'
      if: matrix.dc == 'gdc-12'
      run: |
        ./dub build --compiler=${{ matrix.dc }}
        ./dub test --compiler=${{ matrix.dc }}
